const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000';

// ---- Types ----
// These TypeScript interfaces mirror the Pydantic schemas in backend/app/models/schemas.py.
// Keeping them in sync manually is the simplest approach for this project size.
// For production, consider using openapi-typescript to auto-generate these from the
// FastAPI OpenAPI spec, eliminating the risk of drift.

export type SeverityLevel = 'critical' | 'high' | 'medium' | 'low' | 'info';

export type AlertStatus =
  | 'new'
  | 'triaging'
  | 'investigating'
  | 'remediating'
  | 'closed'
  | 'false_positive';

export interface AlertCreate {
  title: string;
  description: string;
  source: string;
  raw_log?: string;
  source_ip?: string;
  destination_ip?: string;
  affected_host?: string;
  iocs?: string[];
}

export interface AlertResponse {
  id: string;
  title: string;
  description: string;
  source: string;
  severity?: SeverityLevel;   // Populated after triage; absent while status is "new"
  status: AlertStatus;
  created_at: string;
  updated_at: string;
  source_ip?: string;
  destination_ip?: string;
  affected_host?: string;
  iocs?: string[];
}

export interface TriageResult {
  alert_id: string;
  severity: SeverityLevel;
  confidence: number;         // 0.0-1.0, output of voting + self-reflection
  reasoning: string;          // Includes vote counts and critique notes when applicable
  recommended_action: string;
  mitre_techniques: string[];
}

export interface ThreatIntelResult {
  alert_id: string;
  related_cves: string[];
  mitre_tactics: string[];
  threat_actors: string[];
  ioc_analysis: string;
  risk_score: number;         // 0.0-10.0, mirrors CVSS scale for familiarity
}

export interface InvestigationResult {
  alert_id: string;
  timeline: Record<string, unknown>[];
  attack_chain: string;
  affected_assets: string[];
  lateral_movement_detected: boolean;
  data_exfiltration_risk: boolean;
  full_analysis: string;
}

export interface RemediationResult {
  alert_id: string;
  immediate_actions: string[];
  short_term_actions: string[];
  long_term_recommendations: string[];
  playbook_reference?: string;
  estimated_effort: string;
}

export interface IncidentReport {
  incident_id: string;
  alert_id: string;
  title: string;
  executive_summary: string;  // Generated by claude-haiku, written for non-technical stakeholders
  severity: SeverityLevel;
  status: 'open' | 'in_progress' | 'resolved' | 'closed';
  triage?: TriageResult;
  threat_intel?: ThreatIntelResult;
  investigation?: InvestigationResult;  // Absent for low/info severity alerts
  remediation?: RemediationResult;
  created_at: string;
  updated_at: string;
}

// SSE event types match the event_type strings emitted by _emit_event() in alerts.py.
export type SSEEventType =
  | 'pipeline_queued'
  | 'agent_started'
  | 'agent_completed'
  | 'duplicate_detected'
  | 'auto_closed'
  | 'pipeline_complete'
  | 'pipeline_error'
  | 'stream_end';

export interface SSEEvent {
  event: SSEEventType;
  data: Record<string, unknown>;
  ts: string;
}

// ---- API Client ----

// Generic fetch wrapper: adds Content-Type, base URL, and error handling.
// Throwing an Error on non-2xx responses lets callers use try/catch uniformly
// instead of checking response.ok at every call site.
async function apiFetch<T>(path: string, options?: RequestInit): Promise<T> {
  const res = await fetch(`${API_BASE}/api/v1${path}`, {
    headers: {
      'Content-Type': 'application/json',
      ...(options?.headers ?? {}),
    },
    ...options,
  });

  if (!res.ok) {
    const text = await res.text().catch(() => 'Unknown error');
    throw new Error(`API error ${res.status}: ${text}`);
  }

  return res.json() as Promise<T>;
}

export async function createAlert(data: AlertCreate): Promise<AlertResponse> {
  // POST returns 202 Accepted immediately. The alert ID in the response is used
  // to subscribe to the SSE stream and poll for the incident report.
  return apiFetch<AlertResponse>('/alerts/', {
    method: 'POST',
    body: JSON.stringify(data),
  });
}

export async function listAlerts(): Promise<AlertResponse[]> {
  return apiFetch<AlertResponse[]>('/alerts/');
}

export async function getAlert(id: string): Promise<AlertResponse> {
  return apiFetch<AlertResponse>(`/alerts/${id}`);
}

export async function getIncident(alertId: string): Promise<IncidentReport> {
  // Returns 404 while the pipeline is still running. The IncidentReportView
  // component retries on 404 until the report appears.
  return apiFetch<IncidentReport>(`/alerts/${alertId}/incident`);
}

export async function listIncidents(): Promise<IncidentReport[]> {
  return apiFetch<IncidentReport[]>('/incidents/');
}

export async function getIncidentById(id: string): Promise<IncidentReport> {
  return apiFetch<IncidentReport>(`/incidents/${id}`);
}

export async function approveAlert(id: string): Promise<void> {
  // HITL approval: calls POST /alerts/{id}/approve which resumes a
  // CRITICAL alert pipeline that was paused by NodeInterrupt in LangGraph.
  await apiFetch<void>(`/alerts/${id}/approve`, { method: 'POST' });
}

export function streamAlertEvents(
  id: string,
  onEvent: (event: SSEEvent) => void
): () => void {
  // SSE (Server-Sent Events): open one long-lived HTTP connection and receive
  // push notifications from the server as pipeline events occur. The browser's
  // native EventSource API handles reconnection automatically on transient failures.
  // This is more efficient than polling GET /alerts/{id} every second because the
  // server only sends data when something actually changes.
  const url = `${API_BASE}/api/v1/alerts/${id}/stream`;
  const source = new EventSource(url);

  source.onmessage = (e) => {
    try {
      const parsed = JSON.parse(e.data) as SSEEvent;
      onEvent(parsed);
    } catch {
      // Ignore malformed events rather than crashing the stream.
    }
  };

  source.onerror = () => {
    // Close on error rather than letting EventSource's auto-reconnect loop forever.
    // The component's useEffect cleanup will re-open the stream if needed.
    source.close();
  };

  // Return a cleanup function so React's useEffect can close the connection
  // when the component unmounts or the alertId changes.
  return () => {
    source.close();
  };
}
